"""catalog taxonomy

Revision ID: 598dee5535e8
Revises: 0d597eefb17b
Create Date: 2026-09-20 15:48:55.848764

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '598dee5535e8'
down_revision: str | Sequence[str] | None = '0d597eefb17b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attributes',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('data_type', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("data_type IN ('TEXT', 'NUMBER', 'SELECT')", name='attributes_data_type_ck'),
    sa.CheckConstraint("key ~ '^[a-z][a-z0-9_]*$'", name='attributes_key_ck'),
    sa.CheckConstraint('char_length(btrim(name)) between 1 and 80', name='attributes_name_ck'),
    sa.CheckConstraint('char_length(key) between 2 and 64', name='attributes_key_len'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='attributes_key_uniq')
    )
    op.create_table('brands',
    sa.Column('name', postgresql.CITEXT(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name='brands_slug_ck'),
    sa.CheckConstraint('char_length(btrim(name)) between 1 and 120', name='brands_name_ck'),
    sa.CheckConstraint('char_length(slug) between 1 and 120', name='brands_slug_len'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='brands_name_uniq'),
    sa.UniqueConstraint('slug', name='brands_slug_uniq')
    )
    op.create_table('categories',
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name='categories_slug_ck'),
    sa.CheckConstraint('char_length(btrim(name)) between 1 and 120', name='categories_name_ck'),
    sa.CheckConstraint('char_length(slug) between 1 and 120', name='categories_slug_len'),
    sa.CheckConstraint('parent_id IS NULL OR parent_id <> id', name='categories_not_own_parent'),
    sa.CheckConstraint('position >= 0', name='categories_position_ck'),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='categories_slug_uniq')
    )
    op.create_index('categories_parent_idx', 'categories', ['parent_id'], unique=False)
    op.create_table('attribute_options',
    sa.Column('attribute_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(btrim(value)) between 1 and 120', name='attribute_options_value_ck'),
    sa.CheckConstraint('sort_order >= 0', name='attribute_options_sort_ck'),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attribute_id', 'value', name='attribute_options_value_uniq'),
    sa.UniqueConstraint('id', 'attribute_id', name='attribute_options_id_attr_uniq')
    )
    op.create_table('category_attributes',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('attribute_id', sa.UUID(), nullable=False),
    sa.Column('required', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('filterable', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('searchable', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_variation', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('position >= 0', name='category_attrs_pos_ck'),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('category_id', 'attribute_id')
    )
    op.create_index('category_attrs_attr_idx', 'category_attributes', ['attribute_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('category_attrs_attr_idx', table_name='category_attributes')
    op.drop_table('category_attributes')
    op.drop_table('attribute_options')
    op.drop_index('categories_parent_idx', table_name='categories')
    op.drop_table('categories')
    op.drop_table('brands')
    op.drop_table('attributes')
    # ### end Alembic commands ###
