"""product schema

Revision ID: b8a284382dfb
Revises: 598dee5535e8
Create Date: 2026-09-20 15:49:55.675937

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8a284382dfb'
down_revision: str | Sequence[str] | None = '598dee5535e8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=5000), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'active', 'inactive')", name='products_status_ck'),
    sa.CheckConstraint('char_length(btrim(name)) between 2 and 200', name='products_name_ck'),
    sa.CheckConstraint('description is null or char_length(description) <= 5000', name='products_description_ck'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'shop_id', name='products_id_shop_uniq')
    )
    op.create_index('products_brand_idx', 'products', ['brand_id'], unique=False)
    op.create_index('products_category_idx', 'products', ['category_id'], unique=False)
    op.create_index('products_shop_status_idx', 'products', ['shop_id', 'status'], unique=False)
    op.create_table('product_attribute_values',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('attribute_id', sa.UUID(), nullable=False),
    sa.Column('option_id', sa.UUID(), nullable=True),
    sa.Column('value_text', sa.String(length=500), nullable=True),
    sa.Column('value_number', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.CheckConstraint('num_nonnulls(option_id, value_text, value_number) = 1', name='pav_exactly_one_value'),
    sa.CheckConstraint('value_text is null or char_length(value_text) <= 500', name='pav_text_len'),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['option_id', 'attribute_id'], ['attribute_options.id', 'attribute_options.attribute_id'], name='pav_option_attribute_fk', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'attribute_id')
    )
    op.create_index('pav_attribute_idx', 'product_attribute_values', ['attribute_id'], unique=False)
    op.create_index('pav_option_idx', 'product_attribute_values', ['option_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('sku_code', sa.String(length=64), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('stock', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'active'"), nullable=False),
    sa.Column('option_key', sa.String(length=512), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active', 'inactive')", name='variants_status_ck'),
    sa.CheckConstraint('char_length(btrim(sku_code)) between 1 and 64', name='variants_sku_ck'),
    sa.CheckConstraint('price >= 0', name='variants_price_ck'),
    sa.CheckConstraint('stock >= 0', name='variants_stock_ck'),
    sa.ForeignKeyConstraint(['product_id', 'shop_id'], ['products.id', 'products.shop_id'], name='variants_product_shop_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'product_id', name='variants_id_product_uniq')
    )
    op.create_index('variants_product_combo_live', 'product_variants', ['product_id', 'option_key'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('variants_product_idx', 'product_variants', ['product_id'], unique=False)
    op.create_index('variants_shop_sku_live', 'product_variants', ['shop_id', 'sku_code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('product_images',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(key) between 1 and 128', name='product_images_key_ck'),
    sa.CheckConstraint('position >= 0', name='product_images_position_ck'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id', 'product_id'], ['product_variants.id', 'product_variants.product_id'], name='product_images_variant_product_fk', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('product_images_product_idx', 'product_images', ['product_id'], unique=False)
    op.create_index('product_images_variant_idx', 'product_images', ['variant_id'], unique=False)
    op.create_table('product_variant_options',
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('attribute_id', sa.UUID(), nullable=False),
    sa.Column('option_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['option_id', 'attribute_id'], ['attribute_options.id', 'attribute_options.attribute_id'], name='pvo_option_attribute_fk', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('variant_id', 'attribute_id')
    )
    op.create_index('pvo_attribute_idx', 'product_variant_options', ['attribute_id'], unique=False)
    op.create_index('pvo_option_idx', 'product_variant_options', ['option_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('pvo_option_idx', table_name='product_variant_options')
    op.drop_index('pvo_attribute_idx', table_name='product_variant_options')
    op.drop_table('product_variant_options')
    op.drop_index('product_images_variant_idx', table_name='product_images')
    op.drop_index('product_images_product_idx', table_name='product_images')
    op.drop_table('product_images')
    op.drop_index('variants_shop_sku_live', table_name='product_variants', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('variants_product_idx', table_name='product_variants')
    op.drop_index('variants_product_combo_live', table_name='product_variants', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('product_variants')
    op.drop_index('pav_option_idx', table_name='product_attribute_values')
    op.drop_index('pav_attribute_idx', table_name='product_attribute_values')
    op.drop_table('product_attribute_values')
    op.drop_index('products_shop_status_idx', table_name='products')
    op.drop_index('products_category_idx', table_name='products')
    op.drop_index('products_brand_idx', table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
