"""identity schema

Revision ID: fcf89444e962
Revises: 
Create Date: 2026-09-13 18:34:35.148624

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fcf89444e962'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema.

    Hand-reviewed additions to the autogenerated body:

    * ``CREATE EXTENSION IF NOT EXISTS citext``. Autogenerate cannot infer this,
      and every ``CITEXT`` column below fails without it. ``citext`` is a trusted
      extension on PostgreSQL 13+, so the database owner can create it without
      superuser rights. Verified against PostgreSQL 16.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.create_table('permissions',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("key ~ '^[a-z][a-z0-9_]*:[a-z][a-z0-9_]*$'", name='permissions_key_ck'),
    sa.CheckConstraint('char_length(description) between 1 and 200', name='permissions_desc_ck'),
    sa.CheckConstraint('char_length(key) between 3 and 64', name='permissions_key_len'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('shops',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('contact_email', postgresql.CITEXT(), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('background_key', sa.String(length=128), nullable=True),
    sa.Column('background_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name='shops_slug_ck'),
    sa.CheckConstraint("website is null or (char_length(website) <= 255 and website ~* '^https?://')", name='shops_website_ck'),
    sa.CheckConstraint('background_key is null or char_length(background_key) <= 128', name='shops_background_key_ck'),
    sa.CheckConstraint('char_length(btrim(name)) between 2 and 80', name='shops_name_ck'),
    sa.CheckConstraint('char_length(slug) between 1 and 80', name='shops_slug_len'),
    sa.CheckConstraint('contact_email is null or char_length(contact_email) <= 254', name='shops_contact_email_ck'),
    sa.CheckConstraint('contact_phone is null or char_length(contact_phone) <= 32', name='shops_contact_phone_ck'),
    sa.CheckConstraint('description is null or char_length(description) <= 300', name='shops_description_ck'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('shops_slug_live', 'shops', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('users',
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('job_title', sa.String(length=80), nullable=True),
    sa.Column('avatar_key', sa.String(length=128), nullable=True),
    sa.Column('avatar_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('avatar_key is null or char_length(avatar_key) <= 128', name='users_avatar_key_ck'),
    sa.CheckConstraint('bio is null or char_length(bio) <= 500', name='users_bio_ck'),
    sa.CheckConstraint('char_length(btrim(full_name)) between 1 and 120', name='users_full_name_ck'),
    sa.CheckConstraint('char_length(email) <= 254', name='users_email_len'),
    sa.CheckConstraint('email = lower(email)', name='users_email_lower'),
    sa.CheckConstraint('job_title is null or char_length(job_title) <= 80', name='users_job_title_ck'),
    sa.CheckConstraint('phone is null or char_length(phone) <= 32', name='users_phone_ck'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('users_email_live', 'users', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('active_shop_id', sa.UUID(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.UUID(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['active_shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['refresh_tokens.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='refresh_tokens_hash_uniq')
    )
    op.create_index('refresh_tokens_expires_idx', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('refresh_tokens_family_idx', 'refresh_tokens', ['family_id'], unique=False)
    op.create_index('refresh_tokens_user_idx', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('roles',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("key ~ '^[a-z][a-z0-9_]*$'", name='roles_key_ck'),
    sa.CheckConstraint('char_length(btrim(name)) >= 1', name='roles_name_ck'),
    sa.CheckConstraint('char_length(key) between 2 and 64', name='roles_key_len'),
    sa.CheckConstraint('deleted_at IS NULL OR shop_id IS NOT NULL', name='roles_system_role_not_deleted'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('roles_shop_key_uniq', 'roles', ['shop_id', 'key'], unique=True, postgresql_where=sa.text('shop_id IS NOT NULL'))
    op.create_index('roles_system_key_uniq', 'roles', ['key'], unique=True, postgresql_where=sa.text('shop_id IS NULL'))
    op.create_table('memberships',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('memberships_user_shop_live', 'memberships', ['user_id', 'shop_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    The ``citext`` extension is deliberately left in place. Dropping a shared
    extension is not this migration's call: another schema in the same database may
    depend on it, and ``DROP EXTENSION`` would take their columns with it.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_permissions')
    op.drop_index('memberships_user_shop_live', table_name='memberships', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('memberships')
    op.drop_index('roles_system_key_uniq', table_name='roles', postgresql_where=sa.text('shop_id IS NULL'))
    op.drop_index('roles_shop_key_uniq', table_name='roles', postgresql_where=sa.text('shop_id IS NOT NULL'))
    op.drop_table('roles')
    op.drop_index('refresh_tokens_user_idx', table_name='refresh_tokens')
    op.drop_index('refresh_tokens_family_idx', table_name='refresh_tokens')
    op.drop_index('refresh_tokens_expires_idx', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('users_email_live', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('users')
    op.drop_index('shops_slug_live', table_name='shops', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('shops')
    op.drop_table('permissions')
    # ### end Alembic commands ###
